### ISSUE TITLE
test step

### ISSUE THREAD

**Issue by yqcong** [sh-ankur/benchmark-fabric#1]
Hi, I want to use this benchmark to test my own fabric network performance, how can I use it

**Comment by YLINR** [comment]
did you solve the problem?

**Comment by yqcong** [comment]
> 你解决了问题吗？

Not yet,there are many problems in the implementation process, do you have any ideas?

> 嗨，我想用这个基准测试我自己的结构网络性能，我该如何使用它

**Comment by YLINR** [comment]
No, I also encountered many problems

**Comment by YLINR** [comment]
@yqcong Did you solve the problem?
